name: example-workflow
on: [push]
jobs:
  hello-world:
    if: github.repository == 'coder7475/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello World!"
  goodbye-moon:
    # if: success() && needs.hello-world.result == 'success'
    # needs: hello-world
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run: echo "Goodbye Moon!"
