name: Context Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  context-job:
    runs-on: ubuntu-latest

    steps:
      - name: My Step
        env:
          MY_ACTION: ${{ github.action }}
        uses: echo "Hello! MY_ACTION"

      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Print steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Print runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
